workflows:
  ios-profile-workflow:
    name: iOS Profile Build (No Code Signing Required)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      vars:
        # App information
        APP_NAME: "AG Tax Schedule"
        BUNDLE_ID: "com.example.agTaxSchedule"

        # Build configuration
        BUILD_NAME: "1.0.0"

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Flutter clean
        script: |
          flutter clean

      - name: Build iOS Profile (No Code Signing)
        script: |
          flutter build ios --profile --no-codesign \
            --build-name=$BUILD_NAME \
            --build-number=$PROJECT_BUILD_NUMBER

      - name: Create IPA structure
        script: |
          cd build/ios/Debug-iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../ag_tax_schedule.ipa Payload/

    artifacts:
      - ag_tax_schedule.ipa
      - build/ios/Debug-iphoneos/Runner.app/**
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
